services:
  web-app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: pinkieit-web-app
    container_name: pinkieit-web-app
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      APACHE_LOG_DIR: /var/log/apache2
    depends_on:
      db:
        condition: service_healthy
      mqtt:
        condition: service_started
    command: ["/usr/local/bin/app-entrypoint.sh"]
    volumes:
      # - .app/laravel:/var/www/html # for development only
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - 18080:80
      - 6001:6001
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - pinkieit

  db:
    image: mariadb:10.11.4
    container_name: pinkieit-db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      #- ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf # my.cnf ファイルが準備できたらコメントを外してください
    networks:
      - pinkieit

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: pinkieit-mqtt-broker
    ports:
      - "18830:1883"  # MQTT標準ポート
    networks:
      - pinkieit
    volumes:
      - ./mqtt/mosquitto/config:/mosquitto/config
      - ./mqtt/mosquitto/data:/mosquitto/data
      - ./mqtt/mosquitto/log:/mosquitto/log      
    restart: unless-stopped

networks:
  pinkieit:
    driver: bridge

volumes:
  dbdata: